language: rust
rust:
  - stable
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo install cargo-audit
  - cargo install cargo-tarpaulin

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo tarpaulin --verbose --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
after_success:
  - npm run coveralls