language: rust
rust:
  - stable
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo tarpaulin --verbose --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
after_success:
  - npm run coveralls